name: dotNetMicroservices
services:
  mongo:
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - .mongodbdata:/data/db
    image: mongo
volumes:
  mongodbdata:
    external: true
    name: mongodbdata
